### ISSUE TITLE
Failure to compile - (Don't have a clue)

### ISSUE THREAD

**Issue by kleversonmorais** [viljamis/vue-design-system#121]
Hey guys, have been working on the DS for the company I work, since yesterday the project has been behaving strange, not compiling and I don't really get it why. No much essentially was changed, I was basically adding values to preexisting tokens, everything was running according to plan. 

This is the log I get for that error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle vue-design-system@3.0.1~prestart: vue-design-system@3.0.1
6 info lifecycle vue-design-system@3.0.1~start: vue-design-system@3.0.1
7 verbose lifecycle vue-design-system@3.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle vue-design-system@3.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/kleverson.morais/Downloads/vue-design-system-master/vue-design-system/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/munki
9 verbose lifecycle vue-design-system@3.0.1~start: CWD: /Users/kleverson.morais/Downloads/vue-design-system-master/vue-design-system
10 silly lifecycle vue-design-system@3.0.1~start: Args: [ '-c',
10 silly lifecycle   'npm-run-all --parallel styleguide theo:onchange theo dev' ]
11 silly lifecycle vue-design-system@3.0.1~start: Returned: code: 1  signal: null
12 info lifecycle vue-design-system@3.0.1~start: Failed to exec start script
13 verbose stack Error: vue-design-system@3.0.1 start: `npm-run-all --parallel styleguide theo:onchange theo dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid vue-design-system@3.0.1
15 verbose cwd /Users/kleverson.morais/Downloads/vue-design-system-master/vue-design-system
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error vue-design-system@3.0.1 start: `npm-run-all --parallel styleguide theo:onchange theo dev`
22 error Exit status 1
23 error Failed at the vue-design-system@3.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any good sould able to help? Cheers.

**Comment by viljamis** [comment]
@kleversonmorais Based on the error message can’t say much to be honest, but have you changed anything on your system recently? Maybe updated node version, the os or something like that? What OS & OS version are you running?
