### ISSUE TITLE
Unable to start after a fresh clone

### ISSUE THREAD

**Issue by SouthRibbleTech** [viljamis/vue-design-system#167]
I am running node 10.15.1 on windows 10
I have cloned the latest version of vue-design-system
npm install
npm start

But I get the following error

```
λ npm start

> vue-design-system@3.5.7 start D:\develop\vue-design-system
> npm-run-all --parallel styleguide theo:onchange theo dev


> vue-design-system@3.5.7 styleguide D:\develop\vue-design-system
> vue-styleguidist server --open --config ./config/docs.config.js


> vue-design-system@3.5.7 theo:onchange D:\develop\vue-design-system
> onchange "./src/tokens/*.yml" -- npm run theo


> vue-design-system@3.5.7 theo D:\develop\vue-design-system
> theo ./src/tokens/tokens.yml --transform web --format map.scss,scss,raw.json,json --dest ./src/assets/tokens


> vue-design-system@3.5.7 dev D:\develop\vue-design-system
> webpack-dev-server --inline --config ./build/webpack.dev.conf.js

✏️  scss tokens created at "src\assets\tokens\tokens.scss"
✏️  map.scss tokens created at "src\assets\tokens\tokens.map.scss"
✏️  raw.json tokens created at "src\assets\tokens\tokens.raw.json"
✏️  json tokens created at "src\assets\tokens\tokens.json"
TypeError: Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at webpackConfig.module.rules.rules.map.rule (D:\develop\vue-design-system\node_modules\vue-styleguidist\scripts\utils\mergeWebpackConfigVueCLI.js:34:20)
    at Array.map (<anonymous>)
    at mergeWebpackConfigVueCLI (D:\develop\vue-design-system\node_modules\vue-styleguidist\scripts\utils\mergeWebpackConfigVueCLI.js:30:38)
    at module.exports (D:\develop\vue-design-system\node_modules\vue-styleguidist\scripts\make-webpack-config.js:70:20)
    at createServer (D:\develop\vue-design-system\node_modules\vue-styleguidist\scripts\create-server.js:7:24)
    at server (D:\develop\vue-design-system\node_modules\vue-styleguidist\scripts\server.js:5:21)
    at commandServer (D:\develop\vue-design-system\node_modules\vue-styleguidist\bin\styleguidist.js:123:19)
    at Object.<anonymous> (D:\develop\vue-design-system\node_modules\vue-styleguidist\bin\styleguidist.js:72:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-design-system@3.5.7 styleguide: `vue-styleguidist server --open --config ./config/docs.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-design-system@3.5.7 styleguide script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\simon\AppData\Roaming\npm-cache\_logs\2019-02-07T19_34_55_904Z-debug.log
ERROR: "styleguide" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-design-system@3.5.7 start: `npm-run-all --parallel styleguide theo:onchange theo dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-design-system@3.5.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\simon\AppData\Roaming\npm-cache\_logs\2019-02-07T19_34_56_150Z-debug.log

D:\develop\vue-design-system (master)
λ node -v
v10.15.1

```

**Comment by SouthRibbleTech** [comment]
same here. There are also about 80 security vulnerabilities which can only be fixed with breaking changes. Not sure if the project can still be active, perhaps @viljamis  can provide an update?
