### ISSUE TITLE
Vue Design System doesn't start, errors with files

### ISSUE THREAD

**Issue by caseytrombley** [viljamis/vue-design-system#207]
Unable to run this repo, after npm install and trying to run npm start there are errors that are not fixable:

design_system $ npm start

> vue-design-system@3.5.7 start /Users/caseytrombley/Development/algaecal/design_system
> npm-run-all --parallel styleguide theo:onchange theo dev

> vue-design-system@3.5.7 theo /Users/caseytrombley/Development/algaecal/design_system
> theo ./src/tokens/tokens.yml --transform web --format map.scss,scss,raw.json,json --dest ./src/assets/tokens

> vue-design-system@3.5.7 theo:onchange /Users/caseytrombley/Development/algaecal/design_system
> onchange "./src/tokens/*.yml" -- npm run theo

> vue-design-system@3.5.7 styleguide /Users/caseytrombley/Development/algaecal/design_system
> vue-styleguidist server --open --config ./config/docs.config.js

> vue-design-system@3.5.7 dev /Users/caseytrombley/Development/algaecal/design_system
> webpack-dev-server --inline --config ./build/webpack.dev.conf.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/caseytrombley/Development/algaecal/design_system/node_modules/theo/bin/theo.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-design-system@3.5.7 theo: `theo ./src/tokens/tokens.yml --transform web --format map.scss,scss,raw.json,json --dest ./src/assets/tokens`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-design-system@3.5.7 theo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/caseytrombley/.npm/_logs/2020-05-01T15_32_55_518Z-debug.log
ERROR: "theo" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-design-system@3.5.7 start: `npm-run-all --parallel styleguide theo:onchange theo dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-design-system@3.5.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by andersonAlmeida** [comment]
I am having the same problem

**Comment by elevatebart** [comment]
it is an error in https://github.com/salesforce-ux/theo
As a work around you can install optimist yourself.

**Comment by andersonAlmeida** [comment]
It worked. Thanks.
